{{ if and .Values.validator .Values.sessionInjection.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polkadot-deployer.sessionKey" . }}
type: Opaque
data:
  grandpa-session-key: {{ .Values.keys.session_grandpa | b64enc }}
  babe-session-key: {{ .Values.keys.session_babe | b64enc }}
  imonline-session-key: {{ .Values.keys.session_imonline | b64enc }}
  parachain-session-key: {{ .Values.keys.session_parachain | b64enc }}
{{- end }}
